---
- name: Ping a server and check connectivity
  hosts: localhost
  tasks:
    - name: Ping a host to check connectivity
      command: ping -c 1 192.0.2.1
      register: ping_result
      ignore_errors: yes

    - name: Check ping result and act accordingly
      debug:
        msg: "Ping failed!"
      when: ping_result.rc != 0

    - name: Continue with tasks if ping is successfulcle
      debug:
        msg: "Ping successful! Proceeding with further tasks."
      when: ping_result.rc == 0
# 111 in dev

# 2222 in dev
